### ISSUE TITLE
Add appropriate phpstan configuration to each harness

### ISSUE THREAD

**Issue by coledave** [inviqa/harness-base-php#43]
To improve general code quality and project consistency add appropriate starting phpstan configurations to each of the harnesses.

- [x] configuration added to harness-drupal8 and part of "composer test-quality"
- [x] configuration added to harness-magento1 and part of "composer test-quality"
- [x] configuration added to harness-magento2 and part of "composer test-quality"
- [ ] configuration added to harness-wordpress and part of "composer test-quality"

**Comment by andytson-inviqa** [comment]
https://github.com/inviqa/harness-base-php/pull/55 - drupal
https://github.com/inviqa/harness-base-php/pull/66 - magento 2
https://github.com/inviqa/harness-base-php/pull/60 - magento 1 - for PHP 7 only, not 5.6

Wordpress not being done due to PHPStan being for object-orientated frameworks and libraries. All of wordpress's codebase would need to be loaded in PHP prior to parsing of the files being tested, and that's not possible with code-branching within the core php files.

I looked at a stubbing tool to just test plugins and themes, but (a) it doesn't stub the constants that are necessary for plugins (b) plugins also use code-branching within the php files itself, causing functions/classes to not be loaded prior to parsing as well.

**Comment by andytson-inviqa** [comment]
for Magento 1, the only way to run it on a PHP 5.6 project is to run in PHP 7.1+ under another container, with the codebase at least being able to be PHP 7.1+ parsable.
